trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'Checkout repository'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd backend
    npm install
  displayName: 'npm install'
  
# Or alternatively, you can use workingDirectory:
# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
#   workingDirectory: $(Build.SourcesDirectory)/backend
